### PR TITLE
Fix compatibility with activerecord

### PR DESCRIPTION
**Pull request by pschambacher**
:octopus::computer:

/cc @bquorning @grosser 

### Steps to merge
* [x] :+1: from the team

### Risks
* None

### CODE REVIEW

**Comment by bquorning** [comment]
Sure :+1:

**Comment by pschambacher** [comment]
@grosser can you please add me to the owners of this gem?

**Comment by grosser** [comment]
I'm not an owner @osheroff / @rhardih can help ...
not sure who owns the zendesk rubygems user

**Comment by rhardih** [comment]
The zendesk rubygems user is under opsteam@zendesk.com. I wrote a confluence article on how to ask for access at some point; try and search for it. (I don't have access anymore)

**Pull request merged**
