### PR TITLE
Rails 5 compatibility

### PR DESCRIPTION
**Pull request by bquorning**
Removing alias_method_chain, testing with Rails 5 and seeing only 1 failing test. @pschambacher @grosser @osheroff, please have a look.

### CODE REVIEW

**Comment by grosser** [comment]
:+1:

**Comment by bquorning** [comment]
@osheroff @pschambacher I need a hand here.

See also rails/rails#19680.

**Comment by pschambacher** [comment]
@bquorning fixed, ActiveRecord version check was only including/prepending for Rails 4, not 5
@grosser we can haz review?

**Comment by grosser** [comment]
:+1:

**Comment by pschambacher** [comment]
@bquorning :shipit:

**Pull request merged**
